# Generated by Django 5.1.4 on 2026-02-23 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_ressource', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('examen', 'Examen'), ('rattrapage', 'Rattrapage'), ('correction', 'Correction')], max_length=20)),
                ('filiere', models.CharField(choices=[('toutes', 'Toutes'), ('genie_logiciel', 'Génie Logiciel'), ('intelligence_artificielle', 'Intelligence Artificielle'), ('securite_informatique', 'Securite Informatique'), ('seiot', 'SEiot'), ('internet_multimedia', 'Internet Multimédia')], max_length=50)),
                ('promotion', models.CharField(choices=[('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3')], max_length=10)),
                ('semestre', models.IntegerField()),
                ('fichier', models.FileField(upload_to='resources/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
