# Generated by Django 5.1.4 on 2026-02-25 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='promotion',
            field=models.CharField(choices=[('l1', 'L1'), ('l2', 'L2'), ('l3', 'L3'), ('m1', 'M1'), ('m2', 'M2')], max_length=10),
        ),
        migrations.CreateModel(
            name='CoursPratique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulte', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('stack', models.JSONField(default=list)),
                ('apis', models.JSONField(default=list)),
                ('etapes', models.JSONField(default=list)),
                ('liens', models.JSONField(default=list)),
                ('fichier_zip', models.FileField(blank=True, null=True, upload_to='cours/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_pratiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cours Pratiques',
                'db_table': 'cours_pratiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(default='Emploi du temps officiel', max_length=255)),
                ('fichier_pdf', models.FileField(upload_to='emploi_temps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_temps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emplois du Temps',
                'db_table': 'emploi_temps',
                'ordering': ['-created_at'],
            },
        ),
    ]
