# Generated by Django 5.1.4 on 2026-02-25 03:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_description_alter_resource_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courspratique',
            name='fichier_zip',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='cours/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='fichier_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='emploi_temps/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fichier',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='resources/%Y/%m/'),
        ),
    ]
